### ISSUE TITLE
preact-router

### ISSUE THREAD

**Issue by vxna** [phoomparin/preact-three#1]
Hey! 

Have you tried this with preact-router? 

Seems like the scene component is never being properly destroyed/unmounted and the whole webgl renderer is added everytime we switched back to the scene page. 

    ...
    WebGL: INVALID_OPERATION: uniform1f: location not for current program
    WebGL: INVALID_OPERATION: uniformMatrix4fv: location is not from current program
    WebGL: too many errors, no more errors will be reported to the console for this context.

This kind of warnings is clearly stated for duplicate renderer.

Thanks.

**Comment by heypoom** [comment]
Thanks!

I haven't tried to use preact-router with this yet, since it's just a tiny experiment to see if Preact and Three would work together. I think I'll need to destroy the renderer with the componentWillUnmount hook and add some kind of checks to prevent the duplication.

**Comment by vxna** [comment]
I'd wait for some updates then, thank you!

**Comment by vxna** [comment]
Hey @phoomparin !

Would be cool if we can investigate it more, still no luck. I've switched back to react for now, so you can test it with it and react-router-dom also. Maybe [this](https://github.com/pixijs/pixi.js/issues/2233#issuecomment-181650433), or [this](https://stackoverflow.com/a/24138800) can help, since pixi is rely on the same WebGL API. 

I've setup a quick sandbox for tests, you can play it [here](https://codesandbox.io/s/mKAOOGZE). Open console and switch routes couple of times, it will show up this: 

    WARNING: Too many active WebGL contexts. Oldest context will be lost.

It's not that error that I mentioned in the first post, just because I was using a more complex scene in my project, but I think it's the same meaning.
